### ISSUE TITLE
dialog error in conversation tool

### ISSUE THREAD

**Issue by swizardlv** [watson-developer-cloud/text-bot#1]
Please check the attached picture. thanks
![dialog error](https://cloud.githubusercontent.com/assets/10117682/18621987/c7be3af4-7e5c-11e6-8c3f-09e059ec8ebf.jpg)

**Comment by germanattanasio** [comment]
@swizardlv we will look into it. Thanks

**Comment by lkrishnamurthy** [comment]
Unable to re-create. Perhaps fixed in later updates of dialog. @swizardlv : Please verify and let us know if this is still the case. Thanks.
