### ISSUE TITLE
Database does not exist.

### ISSUE THREAD

**Issue by frostchick** [watson-developer-cloud/text-bot#14]
when i run text-bot application locally, i got this error message : "Database does not exist."
get: function(params, callback) {
    botdb.get(params, function(err, response) {
      if (err) {
        if (err.error !== 'not_found') {
          return callback(err);
        } else {
          return callback(null);
        }
      } else {
        return callback(null, response);
      }
    });
in cloudant connect db... 
i already completed all step  in the Getting Started but i did not see any tutorial for create database step...

**Comment by frostchick** [comment]
i solved this bug by created manually database name botdb on IBM dashboard website. But when i run app and type boston , i got this error "Error http status 404" when call api Weather. The response.statusCode was return 404.
` request({
      method: 'GET',
      url: WEATHER_URL + '/v3/location/search',
      qs: qString
    }, function(err, response, body) {
      if (err) {
        callback(err);
      } else if(response.statusCode != 200) {
        callback('Error http status: ' + response.statusCode); <-- errror here 404
      } else if (body.errors && body.errors.length > 0){
        callback(body.errors[0].error.message);
      } else {
        debug('geoLocation for: %s is: %', params.name, JSON.stringify(body.location));

        var location = body.location;
        if (location.length > 0 ) {
          location = location[0];
        }
        var statesByCity = { };

        // Check to see if the city is in multiple states
        if (!Array.isArray(location.adminDistrict)){
          var state = location.adminDistrict;
          statesByCity[state] = {
            longitude: location.longitude,
            latitude: location.latitude
          };
        } else {
          location.adminDistrict.forEach(function(state, i) {
          // Avoid duplicates
          if (!statesByCity[state]){
          statesByCity[state] = {
            longitude: location.longitude[i],
            latitude: location.latitude[i]
          };
        };
        });
      };
        callback(null, { states: statesByCity });
      }
    });
  },`

Help please anyone :(

**Comment by lkrishnamurthy** [comment]
Fixed in #19.
