### ISSUE TITLE
Problem to run locally

### ISSUE THREAD

**Issue by michgutz** [watson-developer-cloud/text-bot#20]
I have executed the npm install and everything seemed to be fine, but when I try to enter to my app in localhost:3000, the host seems to be down.

If I push the application to Bluemix, everything works fine.

**Comment by kognate** [comment]
You'll need to add your credentials from bluemix when you run it locally.

**Comment by michgutz** [comment]
Thanks for the response. Where do I add them? In the env file? Thanks in advance.

**Comment by kognate** [comment]
Yes, you can add them in the `.env` file.  There is a file named `.env.example` that shows the possible values.  You can use the `cf env` command or the bluemix web console to get the credentials for the bluemix services.

**Comment by michgutz** [comment]
Sorry, I'm new to npm. I just needed to run npm start after the npm install command. I suggest add that little step in the 'Running locally' section.

Thank you.

**Comment by kognate** [comment]
Thanks for the feedback.
