### ISSUE TITLE
Not able to get response from bot when integrated with Facebook

### ISSUE THREAD

**Issue by UrmiSahoo** [watson-developer-cloud/text-bot#21]
Hi,
I am not able to get any response from the weatherbot when integrated with facebook messenger

**Comment by lkrishnamurthy** [comment]
Did you try running this locally first ? If not, I'd follow instructions using BotKit and install tunnelme first. Let me know if you are able to do that.  I just tested it and it seem to be working fine on my local.

**Comment by germanattanasio** [comment]
This is probably something to describe in the README.md. Definitely related to #22.
