### ISSUE TITLE
Error: service offering alchemy_api not found

### ISSUE THREAD

**Issue by katheris** [watson-developer-cloud/text-bot#33]
When running the command "cf create-service alchemy_api free alchemy-language-service" as described in the readme I get the error message "Service offering alchemy_api not found"

**Comment by katheris** [comment]
I've done some investigating and it looks like the Alchemy Language service has been replaced by the Natural Language Understanding service (https://console.ng.bluemix.net/catalog/services/natural-language-understanding) Are there any plans to update this app to use the new service?

**Comment by germanattanasio** [comment]
We have this in our backlog @katheris.
