### ISSUE TITLE
Add notes to right panel

### ISSUE THREAD

**Issue by Lhuihui** [watson-developer-cloud/text-bot#8]
Add special notes to the right panel, telling user weather is only available for US cities.

<img width="368" alt="screen shot 2016-09-29 at 11 56 21 am" src="https://cloud.githubusercontent.com/assets/2365989/18972664/b461551c-865f-11e6-8961-6d5a032455fb.png">

**Comment by Lhuihui** [comment]
@lkrishnamurthy

**Comment by lkrishnamurthy** [comment]
Fixed.
